import { useCallback, useEffect, useRef, useState } from 'react'
import { api } from '../api'
import type { PricingActiveConfig, PricingDraft, PricingError, PricingHelper, PricingParameter, PricingPreviewResponse, PricingUnit } from '../types'
import { SpotlightCard } from './reactbits/SpotlightCard'

type EditableParameter = { name:string; value:number|null; valueText:string; unit:PricingUnit|''; required:boolean; removable:boolean }
type EditableDraft = { parameters:EditableParameter[]; helpers:PricingHelper[]; formulas:{net_proceeds:string;profit_threshold:string} }
const units:{value:PricingUnit;label:string}[]=[{value:'eur',label:'EUR · tiền'},{value:'rate',label:'Tỷ lệ · số thập phân'},{value:'vnd_per_eur',label:'VND / EUR'}]
const finite=(v:string)=>v.trim()&&Number.isFinite(Number(v))?Number(v):null
const structuredErrors=(error:unknown):PricingError[]=>{const payload=(error as {payload?:unknown})?.payload;if(!payload||typeof payload!=='object')return[];const errors=(payload as {errors?:unknown}).errors;if(!Array.isArray(errors))return[];return errors.filter((item):item is PricingError=>Boolean(item&&typeof item==='object'&&typeof (item as Record<string,unknown>).field==='string'&&typeof (item as Record<string,unknown>).code==='string'&&typeof (item as Record<string,unknown>).message==='string'))}
const keyOf=(d:EditableDraft)=>JSON.stringify({parameters:d.parameters.map(({name,valueText,unit})=>({name,valueText,unit})),helpers:d.helpers,formulas:d.formulas})
const draftOf=(config:PricingActiveConfig):EditableDraft=>({parameters:config.parameters.map((p:PricingParameter)=>({name:p.name,value:p.value,valueText:String(p.value),unit:p.unit,required:p.required,removable:p.removable})),helpers:config.helpers.map(h=>({...h})),formulas:{...config.formulas}})
type Props={onApplied:()=>void;onDirtyChange:(dirty:boolean)=>void;onLogout?:()=>void}
export default function PricingSettingsPage({onApplied,onDirtyChange,onLogout}:Props){
 const [active,setActive]=useState<PricingActiveConfig|null>(null),[draft,setDraft]=useState<EditableDraft>({parameters:[],helpers:[],formulas:{net_proceeds:'',profit_threshold:''}}),[revision,setRevision]=useState(''),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[stale,setStale]=useState(false),[hammer,setHammer]=useState(''),[cost,setCost]=useState(''),[preview,setPreview]=useState<PricingPreviewResponse|null>(null),[errors,setErrors]=useState<PricingError[]>([]),[message,setMessage]=useState(''),[previewing,setPreviewing]=useState(false),[applying,setApplying]=useState(false),[baseline,setBaseline]=useState(''),[approval,setApproval]=useState<string|null>(null);const previewSequence=useRef(0)
 const dirty=Boolean(baseline)&&keyOf(draft)!==baseline
 const load=useCallback(async()=>{setLoading(true);setLoadError('');try{const r=await api.pricingConfig();const d=draftOf(r.active);setActive(r.active);setRevision(r.active.revision);setDraft(d);setBaseline(keyOf(d));setPreview(null);setErrors([]);setApproval(null);setStale(false)}catch(e){setLoadError(e instanceof Error?e.message:'Không tải được cấu hình tính toán.')}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load]);useEffect(()=>{onDirtyChange(dirty)},[dirty,onDirtyChange]);useEffect(()=>{previewSequence.current+=1;setPreview(null);setErrors([]);setApproval(null)},[draft,hammer,cost]);useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[dirty])
 const setParam=(i:number,patch:Partial<EditableParameter>)=>setDraft(d=>({...d,parameters:d.parameters.map((p,n)=>n===i?{...p,...patch}:p)}));const setHelper=(i:number,patch:Partial<PricingHelper>)=>setDraft(d=>({...d,helpers:d.helpers.map((h,n)=>n===i?{...h,...patch}:h)}))
 const build=():{draft:PricingDraft;errors:PricingError[]}=>{const es:PricingError[]=[];const parameters:PricingDraft['parameters']=[];draft.parameters.forEach((p,i)=>{const f=`parameters[${i}]`;if(!p.name.trim())es.push({field:`${f}.name`,code:'missing_name',message:'Tên tham số không được để trống.'});if(!p.unit)es.push({field:`${f}.unit`,code:'missing_unit',message:'Chọn đơn vị cho tham số.'});if(p.value===null)es.push({field:`${f}.value`,code:'invalid_number',message:'Nhập một số hữu hạn, không để trống.'});if(p.name.trim()&&p.unit&&p.value!==null)parameters.push({name:p.name.trim(),value:p.value,unit:p.unit})});draft.helpers.forEach((h,i)=>{if(!h.name.trim())es.push({field:`helpers[${i}].name`,code:'missing_name',message:'Tên helper không được để trống.'});if(!h.expression.trim())es.push({field:`helpers[${i}].expression`,code:'missing_expression',message:'Nhập biểu thức cho helper.'})});if(!draft.formulas.net_proceeds.trim())es.push({field:'formulas.net_proceeds',code:'missing_expression',message:'Công thức bắt buộc không được để trống.'});if(!draft.formulas.profit_threshold.trim())es.push({field:'formulas.profit_threshold',code:'missing_expression',message:'Công thức bắt buộc không được để trống.'});return{draft:{parameters,helpers:draft.helpers.map(h=>({name:h.name.trim(),expression:h.expression.trim()})),formulas:{net_proceeds:draft.formulas.net_proceeds.trim(),profit_threshold:draft.formulas.profit_threshold.trim()}},errors:es}}
 const previewKey=()=>JSON.stringify({draft:build().draft,hammer,cost,revision});
 const runPreview=async()=>{const sequence=++previewSequence.current;setPreview(null);setErrors([]);setMessage('');setApproval(null);const b=build(),he=finite(hammer),ce=finite(cost);const es=[...b.errors];if(he===null)es.push({field:'inputs.hammer_eur',code:'invalid_number',message:'Nhập một số hữu hạn để chạy thử.'});if(ce===null)es.push({field:'inputs.cost_eur',code:'invalid_number',message:'Nhập một số hữu hạn để chạy thử.'});if(es.length){setErrors(es);return}setPreviewing(true);try{const r=await api.previewPricingConfig({draft:b.draft,inputs:{hammer_eur:he!,cost_eur:ce!}});if(sequence!==previewSequence.current)return;setPreview(r);if(r.active_revision!==revision){setStale(true);setErrors([{field:'revision',code:'stale_revision',message:'Cấu hình đã thay đổi. Hãy tải lại trước khi áp dụng.'}])}else if(r.errors.length)setErrors(r.errors);else if(r.valid&&r.preview)setApproval(previewKey())}catch(e){if(sequence!==previewSequence.current)return;const typed=structuredErrors(e);if(typed.length)setErrors(typed);else setMessage(e instanceof Error?e.message:'Không thể chạy thử cấu hình.')}finally{if(sequence===previewSequence.current)setPreviewing(false)}}
 const apply=async()=>{setErrors([]);if(stale){setMessage('Cấu hình đã có phiên bản mới. Hãy tải lại rồi xem lại thay đổi.');return}const b=build();if(b.errors.length){setErrors(b.errors);return}if(!preview?.valid||!preview.preview||approval!==previewKey()){setMessage('Hãy chạy Preview thành công cho đúng bản nháp và dữ liệu mẫu trước khi áp dụng.');return}setApplying(true);try{const r=await api.applyPricingConfig({expected_revision:revision,draft:b.draft});const d=draftOf(r.active);setActive(r.active);setRevision(r.active.revision);setDraft(d);setBaseline(keyOf(d));setPreview(null);setErrors([]);setStale(false);setApproval(null);setMessage('Đã áp dụng cấu hình tính toán mới.');onApplied()}catch(e){const typed=structuredErrors(e);if((e as {status?:number}).status===409){setStale(true);setMessage('Cấu hình đã có phiên bản mới. Hãy tải lại rồi xem lại thay đổi.')}else if(typed.length)setErrors(typed);else setMessage(e instanceof Error?e.message:'Không thể áp dụng cấu hình.')}finally{setApplying(false)}}
 const addParam=()=>setDraft(d=>({...d,parameters:[...d.parameters,{name:'',value:null,valueText:'',unit:'',required:false,removable:true}]}));const addHelper=()=>setDraft(d=>({...d,helpers:[...d.helpers,{name:'',expression:''}]}));
 const removeParam=(i:number)=>{const p=draft.parameters[i];if(p?.removable&&window.confirm(`Xoá tham số "${p.name||'chưa đặt tên'}" khỏi bản nháp?`))setDraft(d=>({...d,parameters:d.parameters.filter((_,n)=>n!==i)}))};const removeHelper=(i:number)=>{const h=draft.helpers[i];if(h&&window.confirm(`Xoá helper "${h.name||'chưa đặt tên'}" khỏi bản nháp?`))setDraft(d=>({...d,helpers:d.helpers.filter((_,n)=>n!==i)}))}
 if(loading)return <section className="page settings-page"><header className="page-header"><div className="page-header-content"><h1>Cấu hình</h1></div></header><div className="form-card settings-state" role="status">Đang tải cấu hình…</div></section>
 if(loadError)return <section className="page settings-page"><header className="page-header"><div className="page-header-content"><h1>Cấu hình</h1></div></header><div className="banner negative" role="alert">{loadError}<button className="secondary" onClick={()=>void load()}>Thử lại</button></div></section>
 return <section className="page settings-page"><header className="page-header"><div className="page-header-content"><h1>Cấu hình</h1></div>{active&&<div className="route-context-badge" aria-label="Phiên bản cấu hình hiện tại"><span className="context-flow">REVISION / {active.revision}</span><span className="context-tag">{active.source==='env-derived'?'ENV-DERIVED / CHƯA LƯU':'PROFILE ACTIVE'}</span></div>}</header>{stale&&<div className="banner warning" role="alert">Cấu hình active đã đổi trong lúc bạn đang sửa. Bản nháp này chưa được áp dụng.<button className="secondary" onClick={()=>void load()}>Tải cấu hình mới</button></div>}{message&&<div className={`banner ${message.startsWith('Đã áp dụng')?'positive':''}`} role="status">{message}</div>}
 <section className="form-card settings-card" aria-labelledby="parameters-title"><div className="form-card-header"><div className="step-indicator">1</div><div><h2 id="parameters-title" className="card-title">Tham số</h2><p className="card-subtitle">Mỗi giá trị phải có đúng đơn vị. Tỷ lệ dùng dạng thập phân, ví dụ 0,05 = 5%.</p></div></div><div className="settings-rows">{draft.parameters.map((p,i)=><div className="settings-row" key={i}><label className="input-label"><span>Tên tham số {p.required&&<span className="required-mark">*</span>}</span><input value={p.name} readOnly={p.required} onChange={e=>setParam(i,{name:e.target.value})} aria-label={`Tên tham số ${i+1}`}/></label><label className="input-label"><span>Giá trị</span><input value={p.valueText} inputMode="decimal" onChange={e=>setParam(i,{valueText:e.target.value,value:finite(e.target.value)})} aria-label={`Giá trị ${p.name||i+1}`}/></label><label className="input-label"><span>Đơn vị</span><select value={p.unit} aria-label={`Đơn vị ${p.name||i+1}`} disabled={p.required} onChange={e=>setParam(i,{unit:e.target.value as PricingUnit})}><option value="" disabled>Chọn đơn vị</option>{units.filter(u=>p.removable?u.value!=='vnd_per_eur':true).map(u=><option key={u.value} value={u.value}>{u.label}</option>)}</select></label>{p.removable?<button className="icon-action" aria-label={`Xoá tham số ${p.name||i+1}`} onClick={()=>removeParam(i)}>×</button>:<span className="required-copy">Bắt buộc</span>}</div>)}</div><button className="secondary add-button" onClick={addParam}>+ Thêm tham số</button><p className="settings-hint">Tham số tiền dùng EUR; tỷ lệ dùng số thập phân (ví dụ 0,1 = 10%); tỷ giá VND / EUR chỉ thuộc cấu hình FX bắt buộc. Tên biến dùng snake_case.</p></section>
 <section className="form-card settings-card" aria-labelledby="helpers-title"><div className="form-card-header"><div className="step-indicator">2</div><div><h2 id="helpers-title" className="card-title">Helper formulas</h2><p className="card-subtitle">Helper có thể dùng tham số, input hệ thống hoặc helper khác; backend sẽ kiểm tra DAG, đơn vị và điều kiện nghịch đảo.</p></div></div>{!draft.helpers.length&&<div className="settings-empty">Chưa có helper. Bạn có thể thêm helper để chia nhỏ công thức.</div>}{draft.helpers.map((h,i)=><div className="helper-row" key={i}><label className="input-label"><span>Tên helper</span><input value={h.name} aria-label={`Tên helper ${i+1}`} onChange={e=>setHelper(i,{name:e.target.value})}/></label><label className="input-label expression-field"><span>Biểu thức</span><input value={h.expression} aria-label={`Biểu thức helper ${i+1}`} onChange={e=>setHelper(i,{expression:e.target.value})}/></label><button className="icon-action" aria-label={`Xoá helper ${h.name||i+1}`} onClick={()=>removeHelper(i)}>×</button></div>)}<button className="secondary add-button" onClick={addHelper}>+ Thêm helper</button></section>
 <section className="form-card settings-card" aria-labelledby="formulas-title"><div className="form-card-header"><div className="step-indicator">3</div><div><h2 id="formulas-title" className="card-title">Công thức bắt buộc</h2><p className="card-subtitle">Chỉ hỗ trợ +, -, *, /, ngoặc, min() và max(). Backend sẽ kiểm tra đơn vị và điều kiện giá nghịch đảo.</p></div></div><div className="formula-list"><label className="input-label"><span>net_proceeds <code>→ EUR</code></span><textarea value={draft.formulas.net_proceeds} rows={2} spellCheck={false} aria-label="Công thức net proceeds" onChange={e=>setDraft(d=>({...d,formulas:{...d.formulas,net_proceeds:e.target.value}}))}/></label><label className="input-label"><span>profit_threshold <code>→ EUR</code></span><textarea value={draft.formulas.profit_threshold} rows={2} spellCheck={false} aria-label="Công thức profit threshold" onChange={e=>setDraft(d=>({...d,formulas:{...d.formulas,profit_threshold:e.target.value}}))}/></label></div><div className="allowed-variables"><span className="settings-hint">Biến hệ thống được phép:</span>{active?.input_variables.map(v=><code key={v.name}>{v.name}</code>)}</div></section>
 <SpotlightCard className="form-card settings-card" aria-labelledby="preview-title"><div className="form-card-header"><div className="step-indicator">4</div><div><h2 id="preview-title" className="card-title">Chạy thử trước khi áp dụng</h2><p className="card-subtitle">Nhập dữ liệu mẫu hữu hạn. Giá trị hiển thị bên dưới do backend trả về.</p></div></div>{dirty&&<p className="settings-hint" role="status">Bản nháp chưa áp dụng. Nếu rời trang, trình duyệt sẽ hỏi trước khi đóng hoặc tải lại.</p>}<div className="sample-grid"><label className="input-label"><span>hammer_eur</span><input value={hammer} onChange={e=>{setHammer(e.target.value);setPreview(null);setApproval(null)}} inputMode="decimal" placeholder="Ví dụ: 1200"/></label><label className="input-label"><span>cost_eur</span><input value={cost} onChange={e=>{setCost(e.target.value);setPreview(null);setApproval(null)}} inputMode="decimal" placeholder="Ví dụ: 800"/></label></div><div className="settings-actions"><button className="secondary" disabled={previewing||applying} onClick={()=>void runPreview()}>{previewing?'Đang chạy thử…':'Preview'}</button><button className="primary" disabled={applying||previewing||approval!==previewKey()} onClick={()=>void apply()}>{applying?'Đang áp dụng…':'Apply cấu hình'}</button></div>{errors.length>0&&<div className="settings-errors" role="alert">{errors.map(e=><p key={`${e.field}-${e.code}`} className="inline-error"><code>{e.code}</code> · {e.field}: {e.message}</p>)}</div>}{preview?.preview&&<div className="preview-results" aria-live="polite"><div className="preview-result-heading"><span>Kết quả preview</span><span>Kết quả active</span></div>{preview.preview.outputs.map(o=><div className="preview-row" key={o.name}><span><strong>{o.label}</strong><code>{o.name}</code></span><strong>{o.formatted}</strong><strong>{preview.preview?.active_outputs.find(a=>a.name===o.name)?.formatted||'Không đủ dữ liệu'}</strong></div>)}</div>}</SpotlightCard>{onLogout&&<div style={{marginTop:'28px',paddingTop:'16px',borderTop:'1px solid var(--rule)',display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:'0.82rem',color:'var(--muted)'}}>Mật khẩu truy cập đã được ghi nhớ trên trình duyệt này.</span><button type="button" className="secondary" style={{fontSize:'0.82rem',padding:'5px 12px'}} onClick={()=>{if(window.confirm('Đăng xuất khỏi thiết bị này? Bạn sẽ cần nhập lại mật khẩu.'))onLogout()}}>Đăng xuất thiết bị này</button></div>}</section>
}

